### PR TITLE
Add Proposed Schema

### PR DESCRIPTION
**Pull request by briancurtin**
I put together a document that uses a [Mermaid "Entity Relationship Diagram"](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram) to put what you sent in the email together with what I had in my head.

Here are some of the differences between what you first sent me and what's in here:

## Events
* I left `date` off because we can figure it out from `start`
* I have `park` and also added `trails` which would be an array (list), this way we can track that we worked at South Table on the Serpentine Trail, or Apex on both the Argos and Pick N Sledge Trails.
* Over time I think it'll make sense to keep track of the land management agency the work was done done for, if/when we do projects outside of JCOS. In Postgres you can make an enumeration (enum) that a string is one of several options, so I think we would just make that list include several groups in the area to start. That way we can more easily find out that we did X hours for JCOS, Y for Lakewood, Z for CT, etc. (I guess CT isn't technically a land management agency, but maintenance of the trail happens through the CT and not USFS/BLM, right? Can figure out those specifics separately).
* I left `success` out as a column primarily because I wasn't sure how it'd be used, but I think I need to know more about what the separate table was for. Would this be for whether the event happened at all (as opposed to cancelled) or is this is we're considering the work successful versus failed? I think a boolean column called `cancelled` would definitely be valuable so we don't count cancelled events in any hours worked.
* I pulled what you had as `event_type` table + `type_id` into a string value that would have a constraint, like `land_manager`. 
* I like the idea for collaborating groups, which I think we could possibly do via an `ENUM` typed column as well. Another option is using a `CHECK` constraint. 
* I left the `problem` stuff out partially because I wasn't sure how it was used, so I'd like to know more, and also because I thought that could be covered in the `description` column. It doesn't feel like we have enough problems going on that we need a whole table for them.

## Collab Group

I left this out because I think it could probably be a `CHECK` constraint or an `ENUM` type, and we might want the `events` row to have multiple instances of groups.

## Problems

I left this one out because I thought it could be covered in description text.

## Participants
* I went with `attended` instead of the show/noshow option.
* I left off whether they were signed up already or signed on-site. Is that a useful distinction we need to make? I haven't had anyone sign up on-site, though I do have the papers in my trunk for it, but I'm not aware of that making a difference. I guess maybe it'd come up if Scott or Matt were trying to track down someone who shows up on our side but not in Offero?

 
Once we agree on what we should store in the database, I think we should merge this and then from that we'd create the actual Postgres schema.

Another table we'll need to think about will deal with user authentication for leaders to create this stuff, but we can alter the table later to add that.

Related: https://github.com/trailrunnervolunteers/trv-website/issues/2

### CODE REVIEW

**Comment by briancurtin** [comment]
Tip: if you click on `View File` on the `database.md` file in the files changed tab, you can see the rendered diagram. I'm not sure why it looks kind of wonky, but it seemed to have a problem rendering when I had comments on some of the lines but at least it shows up now:

Screen Shot 2022-03-06 at 15 52 54

**Review by Prmurray — COMMENTED** [review]
the enum types make things simpler.  that last enum `groups` is for when we work with comba or run clubs? We could just alter the table to add more enums after it is created, right?

I like the `land management` column. I might try bringing people up to my CT section, so it would be nice to have a way to differentiate.  we don't need to get in the weeds about it, but work on the Colorado Trail is done in coordination with the Colorado Trail Foundation, but we are covered under the USFS' insurance policy...so I think we would technically be working with USFS?

my `problem` column was overkill.  i was thinking of broken tools or having the police called.  but that can all just be addressed in the description

I have had one person show up and join us at an event, so it isn't something that will happen often.

my thought on the success table was if it did not happen, we could keep track of why. Weather and lack of participants were the two that came to mind.  I think that was overkill as well.  

the only other thing I don't think we addressed was whether the event was open or closed, which sort of goes in line with my `success` column.  that way we could only have 'open' events on the list for when the crew leaders go on the site to close them out.  and once the email got sent to Scott, it would 'close' the event out.

**Comment by briancurtin** [comment]
> the enum types make things simpler. that last enum `groups` is for when we work with comba or run clubs? We could just alter the table to add more enums after it is created, right?

Thinking more about it, collaborators would make sense as a table than an enum. That one's a little more likely to be modified over time, whether it's COMBA or GMR, or we do a day and bring my Elastic coworkers out. That might be a nice stat to have on the website, like "We've worked with {x} groups in 2022" and that's a `SELECT COUNT(*) FROM collaborators;` — that'd be much easier and more dynamic than figuring out what the column constraint or enum values are.

> I like the `land management` column. I might try bringing people up to my CT section, so it would be nice to have a way to differentiate. we don't need to get in the weeds about it, but work on the Colorado Trail is done in coordination with the Colorado Trail Foundation, but we are covered under the USFS' insurance policy...so I think we would technically be working with USFS?

I was thinking about that a while ago because I read an email from the CDT about adopting sections, then read a lot about that, wanted to do it, found it'd be USFS, then realized maybe I have enough other stuff to do lol. But maybe I will. 

This one I think could be an enum because yeah, whether it's CT or CDT, it's USFS as the real land manager. Then you'd probably have `CT` in the `trails` column and like `Arapahoe National Forest` or whatever as the `park` value.

I think this column _does_ make sense as an enum, and thinking ahead to include a few in the area it'd probably be `JCOS, CPW, USFS, Lakewood`. Scott's been working with Boulder OSMP for a while, so if Boulder people got involved and ran stuff there, that'd be an addition to make.

> my `problem` column was overkill. i was thinking of broken tools or having the police called. but that can all just be addressed in the description
> 
> I have had one person show up and join us at an event, so it isn't something that will happen often.
> 
> my thought on the success table was if it did not happen, we could keep track of why. Weather and lack of participants were the two that came to mind. I think that was overkill as well.
> 
> the only other thing I don't think we addressed was whether the event was open or closed, which sort of goes in line with my `success` column. that way we could only have 'open' events on the list for when the crew leaders go on the site to close them out. and once the email got sent to Scott, it would 'close' the event out.

Ah, yeah that's a good idea. I think `closed` makes sense for that and defaulting to `false`, and as a part of hitting submit on sending out event description + pictures that updates it to `true`. That'd make for a nice way to have events shown when we login that are `closed=false` so we see what's either coming up or what's needing to be submitted.

**Comment by briancurtin** [comment]
I'll push a change for those ideas later today.

**Comment by Prmurray** [comment]
great, it sounds like we're on the same page.

**Review by Prmurray — APPROVED** [review]

**Comment by briancurtin** [comment]
One thing I thought about was that we'll need something for user authentication, which could be on the `volunteers` table, but that'll depend a bit on how we handle authentication in the first place. Can come back to that later.

**Pull request merged**
