### PR TITLE
Setup the repo for Flask

### PR DESCRIPTION
**Pull request by briancurtin**
This change does a bunch of stuff to get us initially setup. This is a larger PR than I was expecting to make, but I think it's all worth doing early. `src/trv/api.py ` and `tests/test_routes.py` are the main things here, and the rest makes doing everything else easier and gets us toward some continuous integration things I need to setup next.

1. It sets up the `trv` package, which is under the `src/` directory, and adds the `setup.py` file to produce an installable package.
2. Inside the `trv` package it does some boilerplate stuff in `src/trv/__init__.py` to create the Flask app, and then creates one Blueprint for an `/api` set of routes. Those are the "backend" routes we'll have for updating or working with the database. We'll probably have another Blueprint maybe called `views` or something that will render the HTML pages, like an `events.html`.
3. It sets up a `tests/` directory that has some tests of the routes that this change adds.
4. This sets up the requirements we'll need and does it via a similar tactic to what I use at work. We'll want `requirements.txt` to not move unless we tell it to, so we use this concept of putting loose requirements in `base-requirements.txt` and `requirements.txt` becomes the "baked" version of it via the `pip freeze` command.
5. Adds a little `scripts/flask-dev.py` script so you can run the dev server without having to deal with environment variables or anything like that.
6. This sets up `pre-commit` so our code is formatted in a uniform way, using a tool called `black` along with doing some things like always trimming whitespace from the ends of lines. When working with multiple people, I've found these sorts of tools really helpful because it takes away a lot of needless differences and keeps those out of code reviews. When we let a tool do the formatting, personal preference for how things look becomes a lot less of what matters in a code review, so we can keep the reviews more focused.

Closes: #3

### CODE REVIEW

**Comment by briancurtin** [comment]
As of commit a83acf6, this adds a "GitHub Action" that runs our tests, aka "Continuous Integration", so now we can make it so PRs don't merge if they have failing tests. I added a "Branch Protection" rule in https://github.com/trailrunnervolunteers/trv-website/settings/branches that makes it so PRs can't be merged if they're failing, which will eventually be required by Heroku because we won't want to automatically deploy broken code.

If you expand the `Show all checks` above the merge button, you'll see that we run tests against Python 3.10, and you'll see a `Details` link that shows what the output of it is.

**Comment by briancurtin** [comment]
Something is up with the `coverage` config because it's writing the coverage report from the tox installed path, which is good, but it can't compare that to the source, which is bad...and I can't seem to get either side to budge. Looking into it.

**Comment by briancurtin** [comment]
Cool! As of 9e2e47a it works. From the bottom of https://github.com/trailrunnervolunteers/trv-website/actions/runs/1971698524 you can see a [html-report](https://github.com/trailrunnervolunteers/trv-website/suites/5631434397/artifacts/183618894) link, which includes the HTML version of the coverage. Downloading that gets you the report that ran, and can see that it's at 72% coverage but the workflow job specifies a failure below 100%. I knew it was below on purpose, so once I get the coverage up it should pass fine.

**Review by Prmurray — APPROVED** [review]
Definitely need to read up on a lot of this.  But the `src/trv/api.py` section looked good to me.

**Comment by briancurtin** [comment]
Merged this as-is. I can't figure out why `coverage` thinks this isn't at 100% coverage because I can clearly see that for each handler it definitely tests the expected case and some failure cases. It reports that we don't test the failure case at any point for any of them. Not sure why, but I wonder if it's about parameterized tests, so I'll look into that.

Ideally I want to make the coverage check block PRs from being merged if they don't have 100% coverage (or maybe bump it down to like 90%?), but between coverage mis-reporting our actual percentage and the fact that I can't seem to figure out how to make that coverage check _report_ any sort of status, I'd rather just move on and make progress than block this project from continuing.

**Pull request merged**
